name: portainer_agent
services:
  agent:
    container_name: portainer_agent
    image: portainer/agent:sts
    ports:
      - '9001:9001'
    pull_policy: always
    restart: always
    volumes:
      - '/:/host'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
      - '/var/run/docker.sock:/var/run/docker.sock'
