name: arcane-agent

services:
  arcane-agent:
    container_name: arcane-agent
    environment:
      - AGENT_MODE=true
      - AGENT_TOKEN=${AGENT_TOKEN}
      - MANAGER_API_URL=${MANAGER_API_URL}
    image: ghcr.io/getarcaneapp/arcane-headless:latest
    ports:
      - '3553:3553'
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data

volumes:
  arcane-data:
